name: lakasa
favicon: null
layout_spectrum: 0.33307511755265296
typography_spectrum: 0.5192118366248906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.15622201492078602
  lightness: 0.3948656937573105
  saturation: 0.43049973039887846
  rhythmicContrast: 0.2719077938236296
purpose: []
